recipe: default.v1
language: vi

pipeline:
  - name: WhitespaceTokenizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "FPTAI/vibert-base-cased"
    from_pt: true

  - name: RegexFeaturizer

  - name: CountVectorsFeaturizer
    analyzer: "word"

  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 3
    max_ngram: 5

  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  - name: RegexEntityExtractor
    use_lookup_tables: true
    use_regexes: true
    use_word_boundaries: false

  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.5
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_action_name: "utter_fallback"
    core_fallback_threshold: 0.3
    enable_fallback_prediction: true
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
assistant_id: 20251031-125521-calm-halo
