recipe: default.v1
language: vi

pipeline:
  - name: WhitespaceTokenizer

  - name: nlu.custom_featurizer.SentenceTransformerFeaturizer
    model_name: "paraphrase-multilingual-MiniLM-L12-v2"
    
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "word"

  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 3
    max_ngram: 5

  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.05

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_action_name: "utter_fallback"
    core_fallback_threshold: 0.3
    enable_fallback_prediction: true
  - name: TEDPolicy
    max_history: 5
    epochs: 60
    constrain_similarities: true
assistant_id: 20251108-121654-brass-ramp
