recipe: default.v1
language: vi

pipeline:
  - name: WhitespaceTokenizer

  
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "FPTAI/vibert-base-cased"
    from_pt: true

    # Regex for patterns only
  - name: RegexEntityExtractor
    case_sensitive: false
    use_lookup_tables: true
    use_regexes: true

    # Char-level only (bền với lỗi chính tả, teencode)
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 3
    max_ngram: 5

  - name: DIETClassifier
    epochs: 120
    transformer_size: 64
    number_of_transformer_layers: 1
    use_masked_language_model: false
    drop_rate: 0.2
    constrain_similarities: true

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    retrieval_intent: faq

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    retrieval_intent: chitchat

  - name: FallbackClassifier
    threshold: 0.55
    ambiguity_threshold: 0.15

policies:
  - name: MemoizationPolicy

  - name: RulePolicy
    core_fallback_threshold: 0.5
    core_fallback_action_name: "utter_fallback"
    enable_fallback_prediction: true

  - name: UnexpecTEDIntentPolicy
    max_history: 10
    epochs: 120

  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
assistant_id: 20251120-185031-rainy-rank
